engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "lib/**"
  - Gemfile.lock
exclude_paths:
  - "spec/*"
